version: '3.3'

services:
  app:
    build: ./app
    restart: always
    depends_on:
      - postgres
    environment:
      - ENV=prod
    networks:
      - traefik
      - internal
    ports:
      - 3000
    secrets:
      - google.api.key
      - postgres.password
    command:
      - ./entry-point.sh
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.atlas.rule=Host(`atlas.markormesher.co.uk`, `www.atlas.markormesher.co.uk`)
      - traefik.http.routers.atlas.middlewares=strip-www@file
      - traefik.http.routers.atlas.tls.certresolver=letsencrypt

  postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres.password

networks:
  internal:
    external: false
  traefik:
    external:
      name: traefik_default

volumes:
  postgres-data:

secrets:
  google.api.key:
    file: ./secrets/google.api.key
  postgres.password:
    file: ./secrets/postgres.password
