version: '3.3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000
    secrets:
      - google.api.key
      - postgres.password

  postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres.password

volumes:
  postgres-data:

secrets:
  google.api.key:
    file: ./secrets/google.api.key
  postgres.password:
    file: ./secrets/postgres.password
