version: '3.3'

services:
  app:
    build: ./app
    depends_on:
      - postgres
    restart: always
    secrets:
      - google.api.key
      - postgres.password
    environment:
      - ENV=dev
    ports:
      - "3003:3000"
    command: ["./wait-for-it/wait-for-it.sh", "postgres:5432", "--timeout=30", "--strict", "--", "node", "./app.js"]

  postgres:
    image: postgres:10.1-alpine
    restart: always
    secrets:
      - postgres.password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres.password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

secrets:
  google.api.key:
    file: ./secrets/google.api.key
  postgres.password:
    file: ./secrets/postgres.password
