// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file atlas/v1/atlas.proto (package atlas.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file atlas/v1/atlas.proto.
 */
export const file_atlas_v1_atlas: GenFile = /*@__PURE__*/
  fileDesc("ChRhdGxhcy92MS9hdGxhcy5wcm90bxIIYXRsYXMudjEiTAoFUGxhY2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIPCgdjb3VudHJ5GAMgASgJEgsKA2xhdBgEIAEoARILCgNsb24YBSABKAEiEgoQR2V0UGxhY2VzUmVxdWVzdCI0ChFHZXRQbGFjZXNSZXNwb25zZRIfCgZwbGFjZXMYASADKAsyDy5hdGxhcy52MS5QbGFjZSI0ChJVcGRhdGVQbGFjZVJlcXVlc3QSHgoFcGxhY2UYASABKAsyDy5hdGxhcy52MS5QbGFjZSI1ChNVcGRhdGVQbGFjZVJlc3BvbnNlEh4KBXBsYWNlGAEgASgLMg8uYXRsYXMudjEuUGxhY2UiIAoSRGVsZXRlUGxhY2VSZXF1ZXN0EgoKAmlkGAEgASgJIhUKE0RlbGV0ZVBsYWNlUmVzcG9uc2UiEgoQQXV0aENoZWNrUmVxdWVzdCITChFBdXRoQ2hlY2tSZXNwb25zZTKyAgoMQXRsYXNTZXJ2aWNlEkQKCUdldFBsYWNlcxIaLmF0bGFzLnYxLkdldFBsYWNlc1JlcXVlc3QaGy5hdGxhcy52MS5HZXRQbGFjZXNSZXNwb25zZRJKCgtVcGRhdGVQbGFjZRIcLmF0bGFzLnYxLlVwZGF0ZVBsYWNlUmVxdWVzdBodLmF0bGFzLnYxLlVwZGF0ZVBsYWNlUmVzcG9uc2USSgoLRGVsZXRlUGxhY2USHC5hdGxhcy52MS5EZWxldGVQbGFjZVJlcXVlc3QaHS5hdGxhcy52MS5EZWxldGVQbGFjZVJlc3BvbnNlEkQKCUF1dGhDaGVjaxIaLmF0bGFzLnYxLkF1dGhDaGVja1JlcXVlc3QaGy5hdGxhcy52MS5BdXRoQ2hlY2tSZXNwb25zZUJBWj9naXRodWIuY29tL21hcmtvcm1lc2hlci9hdGxhcy9pbnRlcm5hbC9hcGlfZ2VuL2F0bGFzL3YxO2F0bGFzdjFiBnByb3RvMw");

/**
 * @generated from message atlas.v1.Place
 */
export type Place = Message<"atlas.v1.Place"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string country = 3;
   */
  country: string;

  /**
   * @generated from field: double lat = 4;
   */
  lat: number;

  /**
   * @generated from field: double lon = 5;
   */
  lon: number;
};

/**
 * Describes the message atlas.v1.Place.
 * Use `create(PlaceSchema)` to create a new message.
 */
export const PlaceSchema: GenMessage<Place> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 0);

/**
 * @generated from message atlas.v1.GetPlacesRequest
 */
export type GetPlacesRequest = Message<"atlas.v1.GetPlacesRequest"> & {
};

/**
 * Describes the message atlas.v1.GetPlacesRequest.
 * Use `create(GetPlacesRequestSchema)` to create a new message.
 */
export const GetPlacesRequestSchema: GenMessage<GetPlacesRequest> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 1);

/**
 * @generated from message atlas.v1.GetPlacesResponse
 */
export type GetPlacesResponse = Message<"atlas.v1.GetPlacesResponse"> & {
  /**
   * @generated from field: repeated atlas.v1.Place places = 1;
   */
  places: Place[];
};

/**
 * Describes the message atlas.v1.GetPlacesResponse.
 * Use `create(GetPlacesResponseSchema)` to create a new message.
 */
export const GetPlacesResponseSchema: GenMessage<GetPlacesResponse> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 2);

/**
 * @generated from message atlas.v1.UpdatePlaceRequest
 */
export type UpdatePlaceRequest = Message<"atlas.v1.UpdatePlaceRequest"> & {
  /**
   * @generated from field: atlas.v1.Place place = 1;
   */
  place?: Place;
};

/**
 * Describes the message atlas.v1.UpdatePlaceRequest.
 * Use `create(UpdatePlaceRequestSchema)` to create a new message.
 */
export const UpdatePlaceRequestSchema: GenMessage<UpdatePlaceRequest> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 3);

/**
 * @generated from message atlas.v1.UpdatePlaceResponse
 */
export type UpdatePlaceResponse = Message<"atlas.v1.UpdatePlaceResponse"> & {
  /**
   * @generated from field: atlas.v1.Place place = 1;
   */
  place?: Place;
};

/**
 * Describes the message atlas.v1.UpdatePlaceResponse.
 * Use `create(UpdatePlaceResponseSchema)` to create a new message.
 */
export const UpdatePlaceResponseSchema: GenMessage<UpdatePlaceResponse> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 4);

/**
 * @generated from message atlas.v1.DeletePlaceRequest
 */
export type DeletePlaceRequest = Message<"atlas.v1.DeletePlaceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message atlas.v1.DeletePlaceRequest.
 * Use `create(DeletePlaceRequestSchema)` to create a new message.
 */
export const DeletePlaceRequestSchema: GenMessage<DeletePlaceRequest> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 5);

/**
 * @generated from message atlas.v1.DeletePlaceResponse
 */
export type DeletePlaceResponse = Message<"atlas.v1.DeletePlaceResponse"> & {
};

/**
 * Describes the message atlas.v1.DeletePlaceResponse.
 * Use `create(DeletePlaceResponseSchema)` to create a new message.
 */
export const DeletePlaceResponseSchema: GenMessage<DeletePlaceResponse> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 6);

/**
 * @generated from message atlas.v1.AuthCheckRequest
 */
export type AuthCheckRequest = Message<"atlas.v1.AuthCheckRequest"> & {
};

/**
 * Describes the message atlas.v1.AuthCheckRequest.
 * Use `create(AuthCheckRequestSchema)` to create a new message.
 */
export const AuthCheckRequestSchema: GenMessage<AuthCheckRequest> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 7);

/**
 * @generated from message atlas.v1.AuthCheckResponse
 */
export type AuthCheckResponse = Message<"atlas.v1.AuthCheckResponse"> & {
};

/**
 * Describes the message atlas.v1.AuthCheckResponse.
 * Use `create(AuthCheckResponseSchema)` to create a new message.
 */
export const AuthCheckResponseSchema: GenMessage<AuthCheckResponse> = /*@__PURE__*/
  messageDesc(file_atlas_v1_atlas, 8);

/**
 * @generated from service atlas.v1.AtlasService
 */
export const AtlasService: GenService<{
  /**
   * @generated from rpc atlas.v1.AtlasService.GetPlaces
   */
  getPlaces: {
    methodKind: "unary";
    input: typeof GetPlacesRequestSchema;
    output: typeof GetPlacesResponseSchema;
  },
  /**
   * @generated from rpc atlas.v1.AtlasService.UpdatePlace
   */
  updatePlace: {
    methodKind: "unary";
    input: typeof UpdatePlaceRequestSchema;
    output: typeof UpdatePlaceResponseSchema;
  },
  /**
   * @generated from rpc atlas.v1.AtlasService.DeletePlace
   */
  deletePlace: {
    methodKind: "unary";
    input: typeof DeletePlaceRequestSchema;
    output: typeof DeletePlaceResponseSchema;
  },
  /**
   * @generated from rpc atlas.v1.AtlasService.AuthCheck
   */
  authCheck: {
    methodKind: "unary";
    input: typeof AuthCheckRequestSchema;
    output: typeof AuthCheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_atlas_v1_atlas, 0);

