// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlace = `-- name: DeletePlace :exec
DELETE FROM places WHERE id = $1
`

func (q *Queries) DeletePlace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlace, id)
	return err
}

const getPlaces = `-- name: GetPlaces :many
SELECT id, name, country, lat, lon FROM places
`

func (q *Queries) GetPlaces(ctx context.Context) ([]Place, error) {
	rows, err := q.db.Query(ctx, getPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlace = `-- name: UpsertPlace :exec
INSERT INTO places (
  id, name, country, lat, lon
) VALUES (
  $1, $2, $3, $4, $5
) ON CONFLICT (id) DO UPDATE SET
  name = $2,
  country = $3,
  lat = $4,
  lon = $5
`

type UpsertPlaceParams struct {
	ID      pgtype.UUID
	Name    string
	Country string
	Lat     float64
	Lon     float64
}

func (q *Queries) UpsertPlace(ctx context.Context, arg UpsertPlaceParams) error {
	_, err := q.db.Exec(ctx, upsertPlace,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.Lat,
		arg.Lon,
	)
	return err
}
